### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by arvinjarvin**

### CODE REVIEW

**Comment by ikv20009** [comment]
Hello! Please I want to get a license for Novosibirsk Airport (UNNT). How do I do this?

**Comment by arvinjarvin** [comment]
Hi. How do you mean?

**Comment by ikv20009** [comment]
We want to draw an APP in Novosibirsk on SimAware (UNNT)

**Comment by arvinjarvin** [comment]
Budget?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ikv20009** [comment]
What should I do now?

**Pull request merged**
